export const V4EngineModel = {
  parts: [
    {
      id: 'Crankshaft',
      path: '/models/V4_Engine/Crankshaft.glb',
      assembled: { x: 0, y: 0.05, z: 0.3 },
      rotation: { x: -Math.PI / 2, y: 0, z: -4.7 }, 
      exploded: { x: 0, y: -0.3, z: 0 },
    },
    {
      id: 'ConnectingRobCap_1',
      path: '/models/V4_Engine/ConnectingRodCap.glb',
      assembled: { x: 0.04, y: 0.05, z: 0.1435 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.15, z: 0.25 },
    },
    {
      id: 'ConnectingRob_1',
      path: '/models/V4_Engine/ConnectingRod.glb',
      assembled: { x: 0.019, y: 0.25, z: 0.1435 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.3, z: 0.25 },
    },
    {
      id: 'Piston_1',
      path: '/models/V4_Engine/Piston.glb',
      assembled: { x: 0.022, y: 0.223, z: 0.1435 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.45, z: 0.25 },
    },
    {
      id: 'PistonPin_1',
      path: '/models/V4_Engine/PistonPin.glb',
      assembled: { x: 0.018, y: 0.25, z: 0.184 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.6, z: 0.25 },
    },
    {
      id: 'ConnectingRobCap_2',
      path: '/models/V4_Engine/ConnectingRodCap.glb',
      assembled: { x: -0.046, y: 0.05, z: 0.031 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.15, z: 0.1 },
    },
    {
      id: 'ConnectingRob_2',
      path: '/models/V4_Engine/ConnectingRod.glb',
      assembled: { x: -0.025, y: 0.25, z: 0.031 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.3,  z: 0.1 },
    },
    {
      id: 'Piston_2',
      path: '/models/V4_Engine/Piston.glb',
      assembled: { x: -0.027, y: 0.223, z: 0.031 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.45, z: 0.1 },
    },
    {
      id: 'PistonPin_2',
      path: '/models/V4_Engine/PistonPin.glb',
      assembled: { x: -0.025, y: 0.25, z: 0.072 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.6,  z: 0.1 },
    },
    {
      id: 'ConnectingRobCap_3',
      path: '/models/V4_Engine/ConnectingRodCap.glb',
      assembled: { x: -0.046, y: 0.05, z: -0.0835 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.15, z: -0.1 },
    },
    {
      id: 'ConnectingRob_3',
      path: '/models/V4_Engine/ConnectingRod.glb',
      assembled: { x: -0.025, y: 0.25, z: -0.0835 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.3,  z: -0.1 },
    },
    {
      id: 'Piston_3',
      path: '/models/V4_Engine/Piston.glb',
      assembled: { x: -0.027, y: 0.223, z: -0.0835 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.45, z: -0.1 },
    },
    {
      id: 'PistonPin_3',
      path: '/models/V4_Engine/PistonPin.glb',
      assembled: { x: -0.025, y: 0.25, z: -0.043 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.6,  z: -0.1 },
    },
    {
      id: 'ConnectingRobCap_4',
      path: '/models/V4_Engine/ConnectingRodCap.glb',
      assembled: { x: 0.04, y: 0.05, z: -0.1985 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.15, z: -0.25 },
    },
    {
      id: 'ConnectingRob_4',
      path: '/models/V4_Engine/ConnectingRod.glb',
      assembled: { x: 0.019, y: 0.25, z: -0.1985 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.3,  z: -0.25 },
    },
    {
      id: 'Piston_4',
      path: '/models/V4_Engine/Piston.glb',
      assembled: { x: 0.022, y: 0.223, z: -0.1985 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.45, z: -0.25 },
    },
    {
      id: 'PistonPin_4',
      path: '/models/V4_Engine/PistonPin.glb',
      assembled: { x: 0.018, y: 0.25, z: -0.158 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.6,  z: -0.25 },
    },
  ],
}