export const RobotGripperModel = {
  parts: [
    {
      id: 'BasePlate',
      path: '/models/RobotGripper/BasePlate.glb',
      assembled: { x: 0, y: 0, z: 0 },
      rotation: { x: -Math.PI / 2, y: 0, z: Math.PI / 1 }, 
      exploded: { x: 0, y: -0.3, z: 0 },
    },
    {
      id: 'Gripper_L',
      path: '/models/RobotGripper/Gripper.glb',
      assembled: { x: -0.001, y: 0, z: 0.09 },
      rotation: { x: Math.PI / 2, y: 0, z: 1.3 }, 
      exploded: { x: 0, y: 0.15, z: 0.25 },
    },
    {
      id: 'Gripper_R',
      path: '/models/RobotGripper/Gripper.glb',
      assembled: { x: -0.001, y: 0, z: 0.09 },
      rotation: { x: -Math.PI / 2, y: 0, z: -1.8 }, 
      exploded: { x: 0, y: 0.15, z: 0.25 },
    },
    {
      id: 'GearLink_1',
      path: '/models/RobotGripper/GearLink_1.glb',
      assembled: { x: -0.012, y: 0.005, z: 0.04 },
      rotation: { x: 0, y: Math.PI, z: Math.PI / 2 }, 
      exploded: { x: 0, y: 0.3, z: 0.25 },
    },
    {
      id: 'GearLink_2',
      path: '/models/RobotGripper/GearLink_2.glb',
      assembled: { x: 0.013, y: 0.005, z: 0.04 },
      rotation: { x: -Math.PI / 2, y: Math.PI , z: -Math.PI / 2 }, 
      exploded: { x: 0, y: 0.3, z: 0.25 },
    },
    {
      id: 'BaseGear',
      path: '/models/RobotGripper/BaseGear.glb',
      assembled: { x: -0.007, y: 0, z: 0.017 },
      rotation: { x: Math.PI, y: -Math.PI, z: -Math.PI / 2 }, 
      exploded: { x: 0, y: 0.45, z: 0.25 },
    },
    {
      id: 'Link_L',
      path: '/models/RobotGripper/Link.glb',
      assembled: { x: -0.004, y: 0.005, z: 0.076 },
      rotation: { x: 0, y: 0, z: Math.PI / 2 }, 
      exploded: { x: 0, y: 0.6, z: 0.25 },
    },
    {
      id: 'Link_R',
      path: '/models/RobotGripper/Link.glb',
      assembled: { x: 0.004, y: 0.005, z: 0.076 },
      rotation: { x: 0, y: 0, z: Math.PI / 2 }, 
      exploded: { x: 0, y: 0.6, z: 0.25 },
    },
    {
      id: 'BaseMountingBracket',
      path: '/models/RobotGripper/BaseMountingBracket.glb',
      assembled: { x: 0, y: 0, z: 0 },
      rotation: { x: 0, y: 0, z: 0 }, 
      exploded: { x: 0, y: 0.15, z: 0.1 },
    },
    {
      id: 'ConnectingRob_2',
      path: '/models/RobotGripper/ConnectingRod.glb',
      assembled: { x: -0.025, y: 0.25, z: 0.031 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.3,  z: 0.1 },
    },
    {
      id: 'Piston_2',
      path: '/models/RobotGripper/Piston.glb',
      assembled: { x: -0.027, y: 0.223, z: 0.031 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.45, z: 0.1 },
    },
    {
      id: 'PistonPin_2',
      path: '/models/RobotGripper/PistonPin.glb',
      assembled: { x: -0.025, y: 0.25, z: 0.072 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.6,  z: 0.1 },
    },
    {
      id: 'ConnectingRobCap_3',
      path: '/models/RobotGripper/ConnectingRodCap.glb',
      assembled: { x: -0.046, y: 0.05, z: -0.0835 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.15, z: -0.1 },
    },
    {
      id: 'ConnectingRob_3',
      path: '/models/RobotGripper/ConnectingRod.glb',
      assembled: { x: -0.025, y: 0.25, z: -0.0835 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.3,  z: -0.1 },
    },
    {
      id: 'Piston_3',
      path: '/models/RobotGripper/Piston.glb',
      assembled: { x: -0.027, y: 0.223, z: -0.0835 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.45, z: -0.1 },
    },
    {
      id: 'PistonPin_3',
      path: '/models/RobotGripper/PistonPin.glb',
      assembled: { x: -0.025, y: 0.25, z: -0.043 },
      rotation: { x: 0, y: 0, z: -Math.PI / 30 }, 
      exploded: { x: 0, y: 0.6,  z: -0.1 },
    },
    {
      id: 'ConnectingRobCap_4',
      path: '/models/RobotGripper/ConnectingRodCap.glb',
      assembled: { x: 0.04, y: 0.05, z: -0.1985 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.15, z: -0.25 },
    },
    {
      id: 'ConnectingRob_4',
      path: '/models/RobotGripper/ConnectingRod.glb',
      assembled: { x: 0.019, y: 0.25, z: -0.1985 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.3,  z: -0.25 },
    },
    {
      id: 'Piston_4',
      path: '/models/RobotGripper/Piston.glb',
      assembled: { x: 0.022, y: 0.223, z: -0.1985 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.45, z: -0.25 },
    },
    {
      id: 'PistonPin_4',
      path: '/models/RobotGripper/PistonPin.glb',
      assembled: { x: 0.018, y: 0.25, z: -0.158 },
      rotation: { x: 0, y: 0, z: Math.PI / 30 }, 
      exploded: { x: 0, y: 0.6,  z: -0.25 },
    },
  ],
}